### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by chalapathi-ct** [mayhapsDev/detectvm#3]
In file included from antivm.cpp:3:
antivm.hpp: In function 'BOOL DetectVM::SelfDelete()':
antivm.hpp:32:74: error: cast from 'HINSTANCE' {aka 'HINSTANCE__*'} to 'int' loses precision [-fpermissive]
   32 |         if((GetEnvironmentVariable(_T("ComSpec"),szFile,MAX_PATH)!=0) &&((int) ShellExecute(0,0,szFile,szCmd,0,SW_HIDE) > 32))
      |                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by 370rokas** [comment]
What compiler, c++ version and flags are you using?

**Comment by 370rokas** [comment]
Try changing this
```cpp
((int) ShellExecute(0,0,szFile,szCmd,0,SW_HIDE) > 32))
```
to this:
```cpp
(ShellExecute(0, 0, szFile, szCmd, 0, SW_HIDE) > (HINSTANCE) 32))
```
Let me know if it fixes it. 😄
